- name: Install Package
  apt:
    pkg: ['mysql-server', 'libmysqlclient-dev']
    state: present

- name: Copy mysqld.conf
  become: yes
  become_user: root
  copy:
    src: "mysqld.cnf"
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Enable and start mysql service
  systemd:
    name: mysql
    state: started
    daemon_reload: yes
    enabled: yes
